[project]
name = "jev-pseudo-relevance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "datasets>=5.0.1",
    "ir-measures>=0.4.3",
    "matplotlib>=3.11.2",
    "openai>=3.24.0",
    "pydantic>=2.13.5",
    "scipy>=1.18.1",
    "tqdm>=4.70.1",
    "typesafe-sdk>=0.7.2",
]
